services:
  - type: web
    name: streamlit-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: "/app/proyecto-resenas-440817-4206c7cd9f78.json"
